export const PRODUCTS = [
  { id:'american-light', name:'American Light', collection:'american', collectionLabel:'American', cut:'Rift‑cut white oak', species:'White Oak (Quercus alba)', cutMethod:'Rift-cut', color:'#DCC9A6', bestFor:'Cabinetry, wall panels, light-filled interiors', finish:'Clear matte lacquer', longDesc:"American Light is a rift-cut white oak veneer prized for its straight, ribbon-like grain and pale honey tone. Rift-cutting slices the log at a slight angle to the growth rings, eliminating the flecking you'd see in quarter-sawn oak and leaving a clean, linear figure that reads as calm and contemporary. It's a favourite for Scandinavian-influenced interiors where you want the warmth of real wood without a busy pattern." },
  { id:'american-zimmer', name:'American Zimmer', collection:'american', collectionLabel:'American', cut:'Fumed oak', species:'White Oak (Quercus alba)', cutMethod:'Fumed, rift-cut', color:'#8E5A34', bestFor:'Feature walls, furniture fronts, bar tops', finish:'Oil finish', longDesc:"Zimmer takes the same rift-cut oak and exposes it to ammonia fumes, a traditional process that reacts with the wood's natural tannins to deepen it into a rich, chocolate-toned brown without any applied stain. The result is colour that lives inside the wood itself, so the grain stays crisp and the tone won't wear or chip like a surface stain would." },
  { id:'athens-light', name:'Athens Light', collection:'athens', collectionLabel:'Athens', cut:'Bleached ash', species:'European Ash (Fraxinus excelsior)', cutMethod:'Crown-cut, bleached', color:'#C7B79A', bestFor:'Ceilings, light joinery, minimalist spaces', finish:'UV-cured clear coat', longDesc:"Athens Light starts as crown-cut ash and is chemically bleached to strip out the wood's natural warmth, leaving an almost ashen, driftwood-grey finish. The bleaching process is carefully controlled so the grain — ash's signature open, wavy figure — stays fully visible even as the background colour goes pale. It suits spaces that want texture without any hint of orange or red undertone." },
  { id:'athens-dark', name:'Athens Dark', collection:'athens', collectionLabel:'Athens', cut:'Smoked ash', species:'European Ash (Fraxinus excelsior)', cutMethod:'Crown-cut, smoked', color:'#4A3223', bestFor:'Moody interiors, hospitality lounges, doors', finish:'Matte lacquer', longDesc:"Where Athens Light is bleached pale, Athens Dark is smoked — kiln-treated at controlled heat and humidity to darken the timber all the way through. The open ash grain takes the smoking process unevenly, creating natural tonal variation from panel to panel that reads as depth rather than inconsistency. It's the collection's go-to for spaces that want drama without going fully black." },
  { id:'berlin-cherrywood', name:'Berlin Cherrywood', collection:'berlin', collectionLabel:'Berlin', cut:'Flat‑cut cherry', species:'American Cherry (Prunus serotina)', cutMethod:'Flat-cut (plain-sliced)', color:'#7A3226', bestFor:'Executive furniture, reception desks, panelling', finish:'Satin lacquer', longDesc:"Flat-cutting cherry parallel to the growth rings produces its classic cathedral-arch figure — the wide, flame-shaped patterns you see repeat down a panelled wall. Cherry also famously darkens with age and light exposure, so a Berlin Cherrywood installation deepens in tone over its first year or two, gaining the patina that makes cherry a long-favoured choice for formal, traditional interiors." },
  { id:'berlin-mahogany', name:'Berlin Mahogany', collection:'berlin', collectionLabel:'Berlin', cut:'Ribbon‑stripe mahogany', species:'Sapele Mahogany (Entandrophragma cylindricum)', cutMethod:'Quarter-cut (ribbon-stripe)', color:'#5C2620', bestFor:'Doors, formal joinery, statement furniture', finish:'Gloss or satin lacquer', longDesc:"Quarter-cutting mahogany produces the tight, alternating ribbon-stripe figure this veneer is named for — a shimmering effect where the stripes appear to shift lightness as you walk past, thanks to the interlocked grain structure of the species. Deep red-brown and lustrous, it's the collection's most formal option, historically associated with fine cabinetry and executive interiors." },
  { id:'burlwood-porcelain', name:'Burlwood Porcelain', collection:'burl', collectionLabel:'Burl', cut:'Figured maple burl', species:'Maple Burl (Acer spp.)', cutMethod:'Burl-cut (rotary from a burl growth)', color:'#C79A5B', bestFor:'Inlay, accent panels, luxury furniture fronts', finish:'High-gloss lacquer', longDesc:"Burl veneers are cut from the gnarled growths that form on a tree in response to stress or injury — the grain inside grows in tight, chaotic swirls rather than straight lines, which is what gives burl its prized, marble-like figuring. Burlwood Porcelain is cut from pale maple burl, producing a soft, creamy background scattered with small dark eyes and swirling grain — no two panels are alike." },
  { id:'burl-walnut', name:'Burl Walnut', collection:'burl', collectionLabel:'Burl', cut:'Figured walnut burl', species:'Walnut Burl (Juglans regia)', cutMethod:'Burl-cut (rotary from a burl growth)', color:'#6E4A2E', bestFor:'Statement furniture, luxury automotive-style interiors', finish:'High-gloss lacquer', longDesc:"The walnut counterpart to Burlwood Porcelain, cut from the same gnarled burl growths but in walnut's naturally darker, chocolate-brown palette. The swirling figure is denser and higher-contrast than the maple version, which is why walnut burl has long been the material of choice for luxury dashboards, watch boxes, and other small-scale, high-impact surfaces." },
  { id:'cairo-camphor', name:'Cairo Camphor', collection:'cairo', collectionLabel:'Cairo', cut:'Camphor burl', species:'Camphor Laurel (Cinnamomum camphora)', cutMethod:'Burl-cut', color:'#A68A5B', bestFor:'Accent walls, bespoke joinery', finish:'Oil finish', longDesc:"Camphor burl brings an unusually loose, cloud-like figure compared to maple or walnut burl, with soft tonal bands running through a warm tan background. The species is also naturally aromatic — camphor wood retains a faint scent long after milling — which has made it a traditional choice for chests and cabinetry as well as decorative veneer." },
  { id:'cairo-fire', name:'Cairo Fire', collection:'cairo', collectionLabel:'Cairo', cut:'Red‑figured veneer', species:'Redwood Burl (Sequoia sempervirens)', cutMethod:'Burl-cut, dyed', color:'#8C2A22', bestFor:'Feature panels, bar fronts, statement ceilings', finish:'Gloss lacquer', longDesc:"Cairo Fire takes a naturally burled redwood base and enhances its colour with a transparent dye, intensifying the wood's inherent red tones into a deep, glowing red-brown. The burl figure still shows through the dye, so the grain character stays authentic — this is the boldest, most saturated veneer in the collection and reads best as a single, deliberate feature rather than an all-over surface." },
  { id:'cairo-amber', name:'Cairo Amber', collection:'cairo', collectionLabel:'Cairo', cut:'Amber burl', species:'Elm Burl (Ulmus spp.)', cutMethod:'Burl-cut', color:'#C9862E', bestFor:'Tabletops, reception counters, cabinetry', finish:'Satin lacquer', longDesc:"Cairo Amber is cut from elm burl, giving a warm honey-amber background threaded with the fine, interlacing grain elm is known for. It sits between the quieter camphor burl and the saturated Cairo Fire in intensity, making it a versatile choice when a space wants burl's organic character without maximum drama." },
  { id:'cherrywood', name:'Cherrywood', collection:'american', collectionLabel:'American', cut:'Natural cherry', species:'American Cherry (Prunus serotina)', cutMethod:'Flat-cut, natural (unstained)', color:'#8B4A32', bestFor:'Cabinetry, furniture, warm residential interiors', finish:'Clear satin lacquer', longDesc:"This is cherry left in its natural state, without the reddening applied to Berlin Cherrywood — a softer, honeyed brown that still carries cherry's characteristic fine, straight grain and occasional small pin knots. It's the most approachable, residential-feeling wood in the catalogue, and like all cherry it will continue to warm in tone with light exposure over time." },
];

export const PROJECTS = [
  { id:'kitchen', room:'Kitchen', gradient:'linear-gradient(135deg,#4a3a2c,#8b6a48)', veneerUsed:'American Zimmer (fumed oak)', scope:'Cabinetry fronts, island panelling', finish:'Oil finish, food-safe sealant', longDesc:"The hotel's back-of-house and show kitchens were unified in fumed oak, chosen for its durability under heat and moisture as much as its tone. Book-matched panels run across the island fronts so the grain lines up continuously, and every face is sealed with a food-safe oil finish that stands up to daily commercial use without dulling the veneer's warmth." },
  { id:'dining-hall', room:'Dining Hall', gradient:'linear-gradient(135deg,#5c3a26,#c9862e)', veneerUsed:'Cairo Amber (elm burl)', scope:'Wall panelling, bar front, ceiling coffers', finish:'Satin lacquer', longDesc:"The main dining hall wraps guests in elm burl panelling from floor to coffered ceiling, using the veneer's organic swirling figure to soften an otherwise large, formal room. The bar front is book-matched from a single burl flitch so the grain mirrors symmetrically either side of the centreline — the single most labour-intensive detail in the installation." },
  { id:'facade', room:'Facade', gradient:'linear-gradient(135deg,#241a14,#5c3a26)', veneerUsed:'Athens Dark (smoked ash)', scope:'Entrance canopy, exterior soffits', finish:'Weather-rated UV lacquer', longDesc:"For the street-facing facade, smoked ash panels were pressed onto a weather-rated substrate and finished with a UV-stable lacquer built for exterior exposure. The deep, smoked tone gives the entrance canopy a quiet, monumental presence at night, when it's lit from below." },
  { id:'lounge', room:'Lounge', gradient:'linear-gradient(135deg,#3a2a1e,#a6743f)', veneerUsed:'Berlin Cherrywood (flat-cut cherry)', scope:'Feature wall, bar shelving', finish:'Satin lacquer', longDesc:"The lounge's cathedral-figured cherry feature wall was the design anchor for the room's whole colour palette — every fabric and finish choice around it was selected to sit against that warm, arched grain. The wood will continue to deepen in tone over its first year in the space, as cherry does." },
  { id:'bedroom', room:'Bedroom', gradient:'linear-gradient(135deg,#2e2018,#6e4a2e)', veneerUsed:'Burl Walnut', scope:'Headboard walls, wardrobe fronts', finish:'Satin lacquer', longDesc:"Guest rooms use burl walnut sparingly — a single headboard wall per room — so its dense, high-contrast figuring reads as a considered accent rather than overwhelming a small space. Wardrobe fronts in the same veneer keep the room's material language consistent without repeating the same panel twice." },
  { id:'reception', room:'Reception', gradient:'linear-gradient(135deg,#4a3223,#c7a06c)', veneerUsed:'Cairo Camphor (camphor burl)', scope:'Reception desk, back wall', finish:'Oil finish', longDesc:"The reception desk and back wall are finished in camphor burl, whose soft, cloud-like figuring photographs well and reads calmly under the space's low, ambient lighting — the first material a guest touches on arrival, chosen for warmth over drama." },
];

export const SERVICES = [
  { num:'01', title:'Veneer Sourcing', desc:"Species and cut selection matched to your project's palette and budget." },
  { num:'02', title:'Panel Fabrication', desc:'Book-matched and slip-matched panels pressed to your substrate of choice.' },
  { num:'03', title:'Finishing & Protection', desc:'UV, lacquer, and oil finishes suited for residential and commercial use.' },
  { num:'04', title:'Installation Support', desc:'On-site consultation with our fabrication partners for a seamless finish.' },
];

export const FILTER_OPTIONS = [
  { id:'all', label:'All' },
  { id:'american', label:'American' },
  { id:'athens', label:'Athens' },
  { id:'berlin', label:'Berlin' },
  { id:'cairo', label:'Cairo' },
  { id:'burl', label:'Burl' },
];

export const PAGE_SIZE = 4;
